import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import {
    products,
    categories,
    brands,
    reviews,
    orderItems,
    orders,
    cartItems,
} from "./schema/index.js";
import dotenv from "dotenv";

dotenv.config();

const seedDatabase = async () => {
    if (!process.env.DB_URL) {
        throw new Error("❌ DATABASE_URL не найден в .env файле");
    }

    const client = postgres(process.env.DB_URL);
    const db = drizzle(client);

    try {
        console.log("🌱 Начинаем заполнение базы данных...");
        console.log("🧹 Очищаем старые данные...");

        // Очищаем в обратном порядке (сначала зависимые таблицы)
        await db.delete(orderItems);
        await db.delete(orders);
        await db.delete(cartItems);
        await db.delete(reviews);
        await db.delete(products);
        await db.delete(brands);
        await db.delete(categories);
        console.log("✅ Таблицы очищены");

        console.log("✅ Таблицы очищены");

        // 1. Категории
        const categoriesData = [
            {
                name: "Смартфоны",
                slug: "smartfony",
                image: "/Categories/smart-phone.svg",
            },
            {
                name: "Ноутбуки",
                slug: "noutbuki",
                image: "/Categories/laptop.svg",
            },
            {
                name: "Планшеты",
                slug: "planshety",
                image: "/Categories/mobile-large.svg",
            },
            {
                name: "Наушники",
                slug: "naushniki",
                image: "/Categories/headphone.svg",
            },
            {
                name: "Умные часы",
                slug: "umnye-chasy",
                image: "/Categories/watch.svg",
            },
            {
                name: "Игровые консоли",
                slug: "igrovye-konsoli",
                image: "/Categories/game-watch.svg",
            },
            {
                name: "Фотоаппараты",
                slug: "fotoapparaty",
                image: "/Categories/photo-camera.svg",
            },
            {
                name: "Мониторы",
                slug: "monitory",
                image: "/Categories/computer-desktop-display.svg",
            },
            {
                name: "Аксессуары",
                slug: "aksessuary",
                image: "/Categories/collection.svg",
            },
            {
                name: "Телевизоры",
                slug: "televizory",
                image: "/Categories/tv.svg",
            },
        ];

        console.log("📁 Добавляем категории...");
        const insertedCategories = await db
            .insert(categories)
            .values(categoriesData)
            .returning();
        console.log(`✅ Добавлено ${insertedCategories.length} категорий`);

        // 2. Бренды
        const brandsData = [
            { name: "Apple", slug: "apple" },
            { name: "Samsung", slug: "samsung" },
            { name: "Sony", slug: "sony" },
            { name: "Xiaomi", slug: "xiaomi" },
            { name: "LG", slug: "lg" },
            { name: "ASUS", slug: "asus" },
            { name: "Lenovo", slug: "lenovo" },
            { name: "Canon", slug: "canon" },
            { name: "Nintendo", slug: "nintendo" },
            { name: "Microsoft", slug: "microsoft" },
        ];

        console.log("🏷️ Добавляем бренды...");
        const insertedBrands = await db
            .insert(brands)
            .values(brandsData)
            .returning();
        console.log(`✅ Добавлено ${insertedBrands.length} брендов`);

        // 3. Продукты (100 товаров)
        const productsData = [
            // СМАРТФОНЫ (15 товаров)
            {
                name: "Apple iPhone 15 Pro Max",
                slug: "iphone-15-pro-max",
                description:
                    "Флагманский смартфон с титановым корпусом, процессором A17 Pro и камерой 48 МП",
                price: 159990,
                oldPrice: 179990,

                stock: 15,
                isActive: true,
                categoryId: insertedCategories[0].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://best-magazin.com/image/cache/catalog/iPhone%2015%20Pro%20Max/Blue/1-800x800.jpg",
                ],
                specifications: {
                    screen: '6.7"',
                    storage: "256GB",
                    ram: "8GB",
                    battery: "4422 mAh",
                },
                rating: 4.9,
                reviewCount: 127,
            },
            {
                name: "Apple iPhone 16 Pro",
                slug: "iphone-16-pro",
                description:
                    "Мощный смартфон с процессором A17 Pro и профессиональной камерой",
                price: 129990,
                oldPrice: 149990,
                stock: 20,
                isActive: true,
                categoryId: insertedCategories[0].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://apple-rostov.com/image/cache/catalog/apple-iphone-16-pro/apple-iphone-16-pro-128-gb-black-titanium-800x800-product_popup.jpg",
                ],
                specifications: {
                    screen: '6.1"',
                    storage: "128GB",
                    ram: "8GB",
                    battery: "3274 mAh",
                },
                rating: 4.8,
                reviewCount: 98,
            },
            {
                name: "Apple iPhone 17",
                slug: "iphone-17",
                description:
                    "Современный iPhone с Dynamic Island и камерой 48 МП",
                price: 89990,
                oldPrice: 99990,
                stock: 30,
                isActive: true,
                categoryId: insertedCategories[0].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://myapple61.ru/image/cache/catalog/iphone/iphone-17-pro/iphone-17-pro-256-gb-cosmic-orange-800x800-product_thumb.jpg",
                ],
                specifications: {
                    screen: '6.1"',
                    storage: "128GB",
                    ram: "6GB",
                    battery: "3349 mAh",
                },
                rating: 4.7,
                reviewCount: 156,
            },
            {
                name: "Samsung Galaxy S24 Ultra",
                slug: "galaxy-s24-ultra",
                description:
                    "Флагман Samsung с AI-функциями, S Pen и камерой 200 МП",
                price: 139990,
                oldPrice: 159990,
                stock: 18,
                isActive: true,
                categoryId: insertedCategories[0].id,
                brandId: insertedBrands[1].id,
                images: [
                    "https://smart-lite.ru/image/cache/catalog/products/samsung/s24ultra/blue/137074_1712570079_photos_0-800x800.jpeg",
                ],
                specifications: {
                    screen: '6.8"',
                    storage: "256GB",
                    ram: "12GB",
                    battery: "5000 mAh",
                },
                rating: 4.8,
                reviewCount: 89,
            },
            {
                name: "Samsung Galaxy S24+",
                slug: "galaxy-s24-plus",
                description: "Премиальный смартфон с AI и отличным дисплеем",
                price: 109990,
                oldPrice: 119990,
                stock: 25,
                isActive: true,
                categoryId: insertedCategories[0].id,
                brandId: insertedBrands[1].id,
                images: [
                    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfAMrDhL5WnhPfIjvOChvURWddhA_6XWcGEA&s",
                ],
                specifications: {
                    screen: '6.7"',
                    storage: "256GB",
                    ram: "12GB",
                    battery: "4900 mAh",
                },
                rating: 4.7,
                reviewCount: 72,
            },
            {
                name: "Xiaomi 14 Ultra",
                slug: "xiaomi-14-ultra",
                description:
                    "Флагман с камерой Leica и процессором Snapdragon 8 Gen 3",
                price: 99990,
                oldPrice: 114990,
                stock: 22,
                isActive: true,
                categoryId: insertedCategories[0].id,
                brandId: insertedBrands[3].id,
                images: [
                    "https://prostoreshop.ru/upload/iblock/3c1/8w7vb9e74a8kw3oe7vr712u12x5a1evq.jpg",
                ],
                specifications: {
                    screen: '6.73"',
                    storage: "512GB",
                    ram: "16GB",
                    battery: "5000 mAh",
                },
                rating: 4.6,
                reviewCount: 64,
            },
            {
                name: "Xiaomi 14",
                slug: "xiaomi-14",
                description: "Компактный флагман с отличной камерой",
                price: 79990,
                oldPrice: 89990,
                stock: 28,
                isActive: true,
                categoryId: insertedCategories[0].id,
                brandId: insertedBrands[3].id,
                images: [
                    "https://mobilochka.ae/image/cache/70add54132d0fa060dab39f34bdab778.jpg",
                ],
                specifications: {
                    screen: '6.36"',
                    storage: "256GB",
                    ram: "12GB",
                    battery: "4610 mAh",
                },
                rating: 4.5,
                reviewCount: 53,
            },
            {
                name: "Samsung Galaxy Z Fold 5",
                slug: "galaxy-z-fold-5",
                description: "Складной смартфон с большим внутренним экраном",
                price: 169990,
                oldPrice: 189990,
                stock: 10,
                isActive: true,
                categoryId: insertedCategories[0].id,
                brandId: insertedBrands[1].id,
                images: [
                    "https://allohastore.ru/image/cache/catalog/samsung/Fold%204/Fold%205/014-galaxy-zfold5-phantomblack-openback-800x800.jpg",
                ],
                specifications: {
                    screen: '7.6"',
                    storage: "256GB",
                    ram: "12GB",
                    battery: "4400 mAh",
                },
                rating: 4.6,
                reviewCount: 41,
            },
            {
                name: "Samsung Galaxy Z Flip 5",
                slug: "galaxy-z-flip-5",
                description: "Компактный складной смартфон в стиле ретро",
                price: 119990,
                oldPrice: 129990,
                stock: 15,
                isActive: true,
                categoryId: insertedCategories[0].id,
                brandId: insertedBrands[1].id,
                images: [
                    "https://allohastore.ru/image/cache/catalog/samsung/Flip%205/023-galaxy-zflip5-%D1%84%D0%B8%D0%BE%D0%BB-800x800.png",
                ],
                specifications: {
                    screen: '6.7"',
                    storage: "256GB",
                    ram: "8GB",
                    battery: "3700 mAh",
                },
                rating: 4.5,
                reviewCount: 38,
            },
            {
                name: "Xiaomi Redmi Note 13 Pro",
                slug: "redmi-note-13-pro",
                description: "Средний сегмент с флагманскими возможностями",
                price: 34990,
                oldPrice: 39990,
                stock: 45,
                isActive: true,
                categoryId: insertedCategories[0].id,
                brandId: insertedBrands[3].id,
                images: [
                    "https://ir.ozone.ru/s3/multimedia-1/c1000/6858830665.jpg",
                ],
                specifications: {
                    screen: '6.67"',
                    storage: "256GB",
                    ram: "8GB",
                    battery: "5100 mAh",
                },
                rating: 4.4,
                reviewCount: 203,
            },
            {
                name: "Apple iPhone 14",
                slug: "iphone-14",
                description: "Проверенный флагман 2022 года",
                price: 79990,
                oldPrice: 89990,
                stock: 35,
                isActive: true,
                categoryId: insertedCategories[0].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://apple-nova.ru/files/thumb/item/1_43.webp?s=800,800,800,800",
                ],
                specifications: {
                    screen: '6.1"',
                    storage: "128GB",
                    ram: "6GB",
                    battery: "3279 mAh",
                },
                rating: 4.6,
                reviewCount: 312,
            },
            {
                name: "Samsung Galaxy A54",
                slug: "galaxy-a54",
                description: "Популярный смартфон среднего класса",
                price: 39990,
                oldPrice: 44990,
                stock: 50,
                isActive: true,
                categoryId: insertedCategories[0].id,
                brandId: insertedBrands[1].id,
                images: [
                    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5tsxAimaJEnMW7GOf27_zIA8evOP7jWnP3Q&s",
                ],
                specifications: {
                    screen: '6.4"',
                    storage: "128GB",
                    ram: "6GB",
                    battery: "5000 mAh",
                },
                rating: 4.3,
                reviewCount: 178,
            },
            {
                name: "Xiaomi Poco X6 Pro",
                slug: "poco-x6-pro",
                description: "Игровой смартфон с мощным процессором",
                price: 34990,
                oldPrice: 39990,
                stock: 40,
                isActive: true,
                categoryId: insertedCategories[0].id,
                brandId: insertedBrands[3].id,
                images: [
                    "https://technolove.ru/upload/iblock/22d/n2h2ka6ru4jq6afjysj33m66isnxzaaj.jpg",
                ],
                specifications: {
                    screen: '6.67"',
                    storage: "256GB",
                    ram: "12GB",
                    battery: "5000 mAh",
                },
                rating: 4.5,
                reviewCount: 145,
            },
            {
                name: "Apple iPhone X",
                slug: "iphone-x",
                description: "Компактный iPhone с процессором A15",
                price: 24990,
                oldPrice: 29990,
                stock: 30,
                isActive: true,
                categoryId: insertedCategories[0].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://myapple61.ru/image/cache/catalog/iphone/iphone-10-x/iphone-10-x-silver-64-gb-1-800x800-product_thumb.jpg",
                ],
                specifications: {
                    screen: '4.7"',
                    storage: "64GB",
                    ram: "4GB",
                    battery: "2018 mAh",
                },
                rating: 4.2,
                reviewCount: 92,
            },
            {
                name: "Samsung Galaxy A34",
                slug: "galaxy-a34",
                description: "Доступный смартфон с AMOLED экраном",
                price: 29990,
                oldPrice: 34990,
                stock: 55,
                isActive: true,
                categoryId: insertedCategories[0].id,
                brandId: insertedBrands[1].id,
                images: [
                    "https://www.samsungstore.ru/_next/image/?url=https%3A%2F%2Fcdn.samsungstore.ru%2Fiblock%2F336%2F3362984deb7fd4c648af3ebe6d32ff5e%2F7ce815873cf036e84b204692be89c506.jpg&w=1080&q=75",
                ],
                specifications: {
                    screen: '6.6"',
                    storage: "128GB",
                    ram: "6GB",
                    battery: "5000 mAh",
                },
                rating: 4.2,
                reviewCount: 134,
            },

            // НОУТБУКИ (15 товаров)
            {
                name: "Apple MacBook Air 15 M3",
                slug: "macbook-air-15-m3",
                description:
                    "Тонкий и лёгкий ноутбук с чипом M3 и 15-дюймовым экраном",
                price: 149990,
                oldPrice: 169990,
                stock: 12,
                isActive: true,
                categoryId: insertedCategories[1].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://apple-rostov.com/image/cache/catalog/apple-macbook-air-15-m3-2024/Apple-MacBook-Air-15-256-Gb-space-gray-M3-2024-800x800-product_popup.jpg",
                ],
                specifications: {
                    screen: '15.3"',
                    processor: "M3",
                    ram: "8GB",
                    storage: "256GB SSD",
                },
                rating: 4.9,
                reviewCount: 87,
            },
            {
                name: "Apple MacBook Pro 14 M3 Pro",
                slug: "macbook-pro-14-m3-pro",
                description:
                    "Профессиональный ноутбук для работы с видео и графикой",
                price: 219990,
                oldPrice: 239990,
                stock: 8,
                isActive: true,
                categoryId: insertedCategories[1].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://apple-rostov.com/image/cache/catalog/apple-macbook-pro-14-m3-2023/apple-macbook-pro-14-m3-pro-512-gb-silver-2023-800x800-product_popup.jpg",
                ],
                specifications: {
                    screen: '14.2"',
                    processor: "M3 Pro",
                    ram: "18GB",
                    storage: "512GB SSD",
                },
                rating: 4.9,
                reviewCount: 64,
            },
            {
                name: "Apple MacBook Pro 16 M3 Max",
                slug: "macbook-pro-16-m3-max",
                description: "Мощнейший ноутбук для профессионалов",
                price: 349990,
                oldPrice: 379990,
                stock: 5,
                isActive: true,
                categoryId: insertedCategories[1].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://mactime.pro/images/thumbnails/800/799/detailed/88/1_84rn-gn_919f-uu_7m7o-ci.jpg",
                ],
                specifications: {
                    screen: '16.2"',
                    processor: "M3 Max",
                    ram: "36GB",
                    storage: "1TB SSD",
                },
                rating: 5.0,
                reviewCount: 42,
            },
            {
                name: "ASUS ROG Zephyrus G14",
                slug: "asus-rog-zephyrus-g14",
                description: "Игровой ноутбук с Ryzen 9 и RTX 4070",
                price: 159990,
                oldPrice: 179990,
                stock: 10,
                isActive: true,
                categoryId: insertedCategories[1].id,
                brandId: insertedBrands[5].id,
                images: [
                    "https://api.technodom.kz/f3/api/v1/images/800/800/igrovoj_noutbuk_14_asus_rog_zephyrus_g14_ryzen_9_8945hs_16_512_rtx4060_8_dga403uv_qs096_279933_2.jpg",
                ],
                specifications: {
                    screen: '14"',
                    processor: "Ryzen 9",
                    ram: "16GB",
                    storage: "1TB SSD",
                },
                rating: 4.7,
                reviewCount: 56,
            },
            {
                name: "Lenovo Legion Pro 7",
                slug: "lenovo-legion-pro-7",
                description: "Топовый игровой ноутбук с RTX 4090",
                price: 289990,
                oldPrice: 319990,
                stock: 6,
                isActive: true,
                categoryId: insertedCategories[1].id,
                brandId: insertedBrands[6].id,
                images: [
                    "https://delta-game.ru/wp-content/uploads/2024/07/lenovo-legion-pro-7-16irx8h-1.webp",
                ],
                specifications: {
                    screen: '16"',
                    processor: "Intel i9",
                    ram: "32GB",
                    storage: "2TB SSD",
                },
                rating: 4.8,
                reviewCount: 38,
            },
            {
                name: "ASUS ZenBook 14",
                slug: "asus-zenbook-14",
                description: "Ультрабук для работы и учёбы",
                price: 89990,
                oldPrice: 99990,
                stock: 18,
                isActive: true,
                categoryId: insertedCategories[1].id,
                brandId: insertedBrands[5].id,
                images: [
                    "https://www.dikotech.ru/app/uploads/asus-zenbook-14-2025-ultra-9v2-gray-32-1tb-oled.webp",
                ],
                specifications: {
                    screen: '14"',
                    processor: "Intel i7",
                    ram: "16GB",
                    storage: "512GB SSD",
                },
                rating: 4.5,
                reviewCount: 73,
            },
            {
                name: "Lenovo ThinkPad X1 Carbon",
                slug: "thinkpad-x1-carbon",
                description: "Бизнес-ноутбук премиум класса",
                price: 179990,
                oldPrice: 199990,
                stock: 9,
                isActive: true,
                categoryId: insertedCategories[1].id,
                brandId: insertedBrands[6].id,
                images: [
                    "https://cdn.xcomweb.ru/upload/pictures/c63/35ur47ojnjmc7rj7ap4e28vfx0wowila/70+8XUK4b2Gnk_600",
                ],
                specifications: {
                    screen: '14"',
                    processor: "Intel i7",
                    ram: "16GB",
                    storage: "512GB SSD",
                },
                rating: 4.7,
                reviewCount: 51,
            },
            {
                name: "Apple MacBook Air 13 M2",
                slug: "macbook-air-13-m2",
                description: "Популярный ноутбук с чипом M2",
                price: 119990,
                oldPrice: 129990,
                stock: 22,
                isActive: true,
                categoryId: insertedCategories[1].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://uralcases.ru/wp-content/uploads/2022/07/macbook-air-m2-silver-800x800-1-600x600.jpg",
                ],
                specifications: {
                    screen: '13.6"',
                    processor: "M2",
                    ram: "8GB",
                    storage: "256GB SSD",
                },
                rating: 4.8,
                reviewCount: 234,
            },
            {
                name: "ASUS TUF Gaming A15",
                slug: "asus-tuf-gaming-a15",
                description: "Надёжный игровой ноутбук",
                price: 99990,
                oldPrice: 114990,
                stock: 15,
                isActive: true,
                categoryId: insertedCategories[1].id,
                brandId: insertedBrands[5].id,
                images: [
                    "https://apple-nova.ru/files/thumb/item/3654626.jpg?s=800,800,800,800",
                ],
                specifications: {
                    screen: '15.6"',
                    processor: "Ryzen 7",
                    ram: "16GB",
                    storage: "512GB SSD",
                },
                rating: 4.4,
                reviewCount: 112,
            },
            {
                name: "Lenovo IdeaPad Gaming 3",
                slug: "ideapad-gaming-3",
                description: "Доступный игровой ноутбук",
                price: 79990,
                oldPrice: 89990,
                stock: 20,
                isActive: true,
                categoryId: insertedCategories[1].id,
                brandId: insertedBrands[6].id,
                images: [
                    "https://apple-nova.ru/files/thumb/item/2881362_1.jpg?s=800,800,800,800",
                ],
                specifications: {
                    screen: '15.6"',
                    processor: "Ryzen 5",
                    ram: "8GB",
                    storage: "512GB SSD",
                },
                rating: 4.3,
                reviewCount: 98,
            },
            {
                name: "ASUS VivoBook 15",
                slug: "vivobook-15",
                description: "Универсальный ноутбук для дома",
                price: 54990,
                oldPrice: 64990,
                stock: 30,
                isActive: true,
                categoryId: insertedCategories[1].id,
                brandId: insertedBrands[5].id,
                images: [
                    "https://apple-nova.ru/files/thumb/item/6789115472.jpg?s=800,800,800,800",
                ],
                specifications: {
                    screen: '15.6"',
                    processor: "Intel i5",
                    ram: "8GB",
                    storage: "256GB SSD",
                },
                rating: 4.2,
                reviewCount: 145,
            },
            {
                name: "Lenovo Yoga 9i",
                slug: "yoga-9i",
                description: "2-в-1 ноутбук с сенсорным экраном",
                price: 139990,
                oldPrice: 159990,
                stock: 11,
                isActive: true,
                categoryId: insertedCategories[1].id,
                brandId: insertedBrands[6].id,
                images: [
                    "https://api.technodom.kz/f3/api/v1/images/800/800/259418_4.jpg",
                ],
                specifications: {
                    screen: '14"',
                    processor: "Intel i7",
                    ram: "16GB",
                    storage: "512GB SSD",
                },
                rating: 4.6,
                reviewCount: 47,
            },
            {
                name: "ASUS ProArt StudioBook",
                slug: "proart-studiobook",
                description: "Для дизайнеров и видеомонтажёров",
                price: 249990,
                oldPrice: 279990,
                stock: 7,
                isActive: true,
                categoryId: insertedCategories[1].id,
                brandId: insertedBrands[5].id,
                images: [
                    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ27aoKPDS2uqBHRN7BZ3SMKd3G4vo9i49I4A&s",
                ],
                specifications: {
                    screen: '16"',
                    processor: "Intel i9",
                    ram: "32GB",
                    storage: "1TB SSD",
                },
                rating: 4.7,
                reviewCount: 29,
            },
            {
                name: "Lenovo Legion Slim 7",
                slug: "legion-slim-7",
                description: "Тонкий игровой ноутбук",
                price: 169990,
                oldPrice: 189990,
                stock: 9,
                isActive: true,
                categoryId: insertedCategories[1].id,
                brandId: insertedBrands[6].id,
                images: [
                    "https://best-magazin.com/image/cache/catalog/product/Noutbuki/Lenovo/Legion%20/noutbuk-lenovo-legion-slim-7-15ach6-harakteristiki-800x800.jpg",
                ],
                specifications: {
                    screen: '16"',
                    processor: "Ryzen 9",
                    ram: "16GB",
                    storage: "1TB SSD",
                },
                rating: 4.6,
                reviewCount: 41,
            },
            {
                name: "ASUS Chromebook Flip",
                slug: "chromebook-flip",
                description: "Бюджетный 2-в-1 на Chrome OS",
                price: 39990,
                oldPrice: 44990,
                stock: 25,
                isActive: true,
                categoryId: insertedCategories[1].id,
                brandId: insertedBrands[5].id,
                images: [
                    "https://torg-pc.ru/upload/resize_cache/iblock/0cc/xxc66gjdgikjc0rif3w1vgmjsc72o3n7/750_650_140cd750bba9870f18aada2478b24840a/Asus-Chromebook-Flip-CX3401FBA-DS32T-CB-1.webp",
                ],
                specifications: {
                    screen: '14"',
                    processor: "MediaTek",
                    ram: "4GB",
                    storage: "64GB eMMC",
                },
                rating: 4.1,
                reviewCount: 67,
            },

            // НАУШНИКИ (15 товаров)
            {
                name: "Apple AirPods Pro 2",
                slug: "airpods-pro-2",
                description: "Премиальные TWS наушники с шумоподавлением",
                price: 24990,
                oldPrice: 27990,
                stock: 40,
                isActive: true,
                categoryId: insertedCategories[3].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://ap-store.su/image/cache/catalog/Content/AirPods/AirPods%20Pro%202%202022/apple-airpods-pro-2-2022-magsafe-800x800.jpeg",
                ],
                specifications: {
                    type: "In-Ear",
                    connectivity: "Bluetooth 5.3",
                    battery: "30 hours",
                },
                rating: 4.8,
                reviewCount: 312,
            },
            {
                name: "Apple AirPods Max",
                slug: "airpods-max",
                description: "Полноразмерные наушники премиум класса",
                price: 64990,
                oldPrice: 69990,
                stock: 15,
                isActive: true,
                categoryId: insertedCategories[3].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://applestore72.ru/upload/iblock/5bf/jnymbax8o477ly0sv5iuutsfasogffzt.jpg",
                ],
                specifications: {
                    type: "Over-Ear",
                    connectivity: "Bluetooth 5.0",
                    battery: "20 hours",
                },
                rating: 4.7,
                reviewCount: 128,
            },
            {
                name: "Sony WH-1000XM5",
                slug: "sony-wh-1000xm5",
                description: "Лучшее шумоподавление на рынке",
                price: 39990,
                oldPrice: 44990,
                stock: 25,
                isActive: true,
                categoryId: insertedCategories[3].id,
                brandId: insertedBrands[2].id,
                images: [
                    "https://doctorhead.ru/upload/dev2fun.imagecompress/webp/resize_cache/iblock/969/auvd09sdtk24x7o8wb0zh0h49p2xo0t1/688_688_1/sony_wh1000xm5_black.webp",
                ],
                specifications: {
                    type: "Over-Ear",
                    connectivity: "Bluetooth 5.2",
                    battery: "30 hours",
                },
                rating: 4.9,
                reviewCount: 267,
            },
            {
                name: "Sony WF-1000XM5",
                slug: "sony-wf-1000xm5",
                description: "Компактные наушники с топовым шумодавом",
                price: 29990,
                oldPrice: 32990,
                stock: 30,
                isActive: true,
                categoryId: insertedCategories[3].id,
                brandId: insertedBrands[2].id,
                images: [
                    "https://video-shoper.ru/upload/iblock/702/9s25q9cje0vjndwx132jx9nej9jz4ljm.webp",
                ],
                specifications: {
                    type: "In-Ear",
                    connectivity: "Bluetooth 5.3",
                    battery: "24 hours",
                },
                rating: 4.8,
                reviewCount: 189,
            },
            {
                name: "Samsung Galaxy Buds2 Pro",
                slug: "galaxy-buds2-pro",
                description: "Флагманские наушники для экосистемы Samsung",
                price: 19990,
                oldPrice: 22990,
                stock: 35,
                isActive: true,
                categoryId: insertedCategories[3].id,
                brandId: insertedBrands[1].id,
                images: [
                    "https://www.samsungstore.ru/_next/image/?url=https%3A%2F%2Fcdn.samsungstore.ru%2Fiblock%2Fac4%2Fac4b3b87403d8ba67b8bed01f8869465%2F3ed65fb1dc1757d6ab84af622e04aa11.jpg&w=1080&q=75",
                ],
                specifications: {
                    type: "In-Ear",
                    connectivity: "Bluetooth 5.3",
                    battery: "18 hours",
                },
                rating: 4.5,
                reviewCount: 143,
            },
            {
                name: "Apple AirPods 3",
                slug: "airpods-3",
                description: "Классические AirPods с пространственным аудио",
                price: 17990,
                oldPrice: 19990,
                stock: 45,
                isActive: true,
                categoryId: insertedCategories[3].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://mobi-s.ru/wp-content/uploads/2019/03/airpods-3-800x533.jpg.webp",
                ],
                specifications: {
                    type: "In-Ear",
                    connectivity: "Bluetooth 5.0",
                    battery: "30 hours",
                },
                rating: 4.6,
                reviewCount: 421,
            },
            {
                name: "Sony WH-CH720N",
                slug: "sony-wh-ch720n",
                description: "Доступные наушники с шумоподавлением",
                price: 12990,
                oldPrice: 14990,
                stock: 40,
                isActive: true,
                categoryId: insertedCategories[3].id,
                brandId: insertedBrands[2].id,
                images: [
                    "https://doctorhead.ru/upload/dev2fun.imagecompress/webp/iblock/ede/w8d8sknix2qcr8h9i4agbbaz0fk1cwnz/sony_WH_CH720N_w_1.webp",
                ],
                specifications: {
                    type: "Over-Ear",
                    connectivity: "Bluetooth 5.2",
                    battery: "35 hours",
                },
                rating: 4.4,
                reviewCount: 178,
            },
            {
                name: "JBL Tune 770NC",
                slug: "jbl-tune-770nc",
                description: "Басовитые наушники с ANC",
                price: 9990,
                oldPrice: 11990,
                stock: 50,
                isActive: true,
                categoryId: insertedCategories[3].id,
                brandId: insertedBrands[2].id,
                images: [
                    "https://cdn1.technopark.ru/technopark/photos_resized/product/1000_1000/668929/1_668929.jpg",
                ],
                specifications: {
                    type: "Over-Ear",
                    connectivity: "Bluetooth 5.3",
                    battery: "44 hours",
                },
                rating: 4.3,
                reviewCount: 156,
            },
            {
                name: "Samsung Galaxy Buds FE",
                slug: "galaxy-buds-fe",
                description: "Бюджетные наушники Samsung",
                price: 9990,
                oldPrice: 11990,
                stock: 55,
                isActive: true,
                categoryId: insertedCategories[3].id,
                brandId: insertedBrands[1].id,
                images: [
                    "https://www.samsungstore.ru/_next/image/?url=https%3A%2F%2Fcdn.samsungstore.ru%2Fiblock%2F373%2F3739dc030270e07794d90ffde50dd997%2Feadea93a2dfaf6912df551aa7cc0a3ac.jpg&w=1080&q=75",
                ],
                specifications: {
                    type: "In-Ear",
                    connectivity: "Bluetooth 5.2",
                    battery: "21 hours",
                },
                rating: 4.2,
                reviewCount: 94,
            },
            {
                name: "Beats Studio Pro",
                slug: "beats-studio-pro",
                description: "Стильные наушники с мощным звуком",
                price: 34990,
                oldPrice: 39990,
                stock: 20,
                isActive: true,
                categoryId: insertedCategories[3].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://best-magazin.com/image/cache/catalog/Beats/Studio%20Pro/StudioProBlack1-800x800.jpg",
                ],
                specifications: {
                    type: "Over-Ear",
                    connectivity: "Bluetooth 5.3",
                    battery: "24 hours",
                },
                rating: 4.5,
                reviewCount: 87,
            },
            {
                name: "Xiaomi Redmi Buds 4 Pro",
                slug: "redmi-buds-4-pro",
                description: "Недорогие наушники с ANC",
                price: 5990,
                oldPrice: 6990,
                stock: 60,
                isActive: true,
                categoryId: insertedCategories[3].id,
                brandId: insertedBrands[3].id,
                images: [
                    "https://xiaomiexclusive.ru/files/thumb/item/1_133.jpg?s=800,800,800,800",
                ],
                specifications: {
                    type: "In-Ear",
                    connectivity: "Bluetooth 5.3",
                    battery: "36 hours",
                },
                rating: 4.3,
                reviewCount: 234,
            },
            {
                name: "Sennheiser Momentum 4",
                slug: "momentum-4",
                description: "Аудиофильские наушники",
                price: 34990,
                oldPrice: 39990,
                stock: 12,
                isActive: true,
                categoryId: insertedCategories[3].id,
                brandId: insertedBrands[2].id,
                images: [
                    "https://doctorhead.ru/upload/dev2fun.imagecompress/webp/iblock/123/2ump09vp6zxtanzwr2wxcv2ekdreihsc/sennheiser_Momentum_4_brown_1.webp",
                ],
                specifications: {
                    type: "Over-Ear",
                    connectivity: "Bluetooth 5.2",
                    battery: "60 hours",
                },
                rating: 4.7,
                reviewCount: 76,
            },
            {
                name: "Bose QuietComfort Ultra",
                slug: "quietcomfort-ultra",
                description: "Легендарное шумоподавление Bose",
                price: 44990,
                oldPrice: 49990,
                stock: 10,
                isActive: true,
                categoryId: insertedCategories[3].id,
                brandId: insertedBrands[2].id,
                images: [
                    "https://bosestore.ru/upload/iblock/080/xgltoauxxs0vu3kmuriv92hlh8xhdljh/bose_quietcomfort_ultra_headphones_white_01.jpg",
                ],
                specifications: {
                    type: "Over-Ear",
                    connectivity: "Bluetooth 5.3",
                    battery: "24 hours",
                },
                rating: 4.8,
                reviewCount: 92,
            },
            {
                name: "Nothing Ear (2)",
                slug: "nothing-ear-2",
                description: "Стильные прозрачные наушники",
                price: 12990,
                oldPrice: 14990,
                stock: 30,
                isActive: true,
                categoryId: insertedCategories[3].id,
                brandId: insertedBrands[3].id,
                images: [
                    "https://main-cdn.sbermegamarket.ru/big1/hlr-system/-12/362/807/664/141/27/600011559630b0.png",
                ],
                specifications: {
                    type: "In-Ear",
                    connectivity: "Bluetooth 5.3",
                    battery: "36 hours",
                },
                rating: 4.4,
                reviewCount: 118,
            },
            {
                name: "Anker Soundcore Liberty 4",
                slug: "soundcore-liberty-4",
                description: "Отличное соотношение цены и качества",
                price: 8990,
                oldPrice: 9990,
                stock: 45,
                isActive: true,
                categoryId: insertedCategories[3].id,
                brandId: insertedBrands[3].id,
                images: [
                    "https://netbox.by/image/catalog/products_2023/Anker-Soundcore-Liberty-4-NC-True-Wireless-Earbuds-blue.jpg",
                ],
                specifications: {
                    type: "In-Ear",
                    connectivity: "Bluetooth 5.3",
                    battery: "28 hours",
                },
                rating: 4.3,
                reviewCount: 167,
            },

            // ИГРОВЫЕ КОНСОЛИ (10 товаров)
            {
                name: "PlayStation 5",
                slug: "playstation-5",
                description: "Игровая консоль нового поколения с SSD",
                price: 54990,
                oldPrice: 59990,
                stock: 20,
                isActive: true,
                categoryId: insertedCategories[5].id,
                brandId: insertedBrands[2].id,
                images: [
                    "https://apple-rostov.com/image/cache/catalog/Consoles/ps-5-slim-digital-800x800-product_popup.jpg",
                ],
                specifications: {
                    storage: "825GB SSD",
                    resolution: "4K",
                    rayTracing: "Yes",
                },
                rating: 4.9,
                reviewCount: 412,
            },
            {
                name: "PlayStation 5 Digital Edition",
                slug: "ps5-digital",
                description: "PS5 без дисковода",
                price: 44990,
                oldPrice: 49990,
                stock: 25,
                isActive: true,
                categoryId: insertedCategories[5].id,
                brandId: insertedBrands[2].id,
                images: [
                    "https://applegod.ru/upload/iblock/ee5/2trq0jz201u9iyyvlogwciu60jek4n84.png",
                ],
                specifications: {
                    storage: "825GB SSD",
                    resolution: "4K",
                    rayTracing: "Yes",
                },
                rating: 4.8,
                reviewCount: 298,
            },
            {
                name: "Xbox Series X",
                slug: "xbox-series-x",
                description: "Мощнейшая консоль от Microsoft",
                price: 54990,
                oldPrice: 59990,
                stock: 18,
                isActive: true,
                categoryId: insertedCategories[5].id,
                brandId: insertedBrands[9].id,
                images: [
                    "https://best-magazin.com/image/cache/catalog/product/Igrovie-pristavki/xbox/igrovaia-pristavka-microsoft-xbox-series-x-800x800.jpg",
                ],
                specifications: {
                    storage: "1TB SSD",
                    resolution: "4K",
                    rayTracing: "Yes",
                },
                rating: 4.8,
                reviewCount: 267,
            },
            {
                name: "Xbox Series S",
                slug: "xbox-series-s",
                description: "Компактная консоль для игр в 1440p",
                price: 29990,
                oldPrice: 34990,
                stock: 30,
                isActive: true,
                categoryId: insertedCategories[5].id,
                brandId: insertedBrands[9].id,
                images: [
                    "https://hi-stores.ru/upload/iblock/825/8258aedd2b99ba7ad0fa11ef59312706.jpg",
                ],
                specifications: {
                    storage: "512GB SSD",
                    resolution: "1440p",
                    rayTracing: "Yes",
                },
                rating: 4.6,
                reviewCount: 189,
            },
            {
                name: "Nintendo Switch OLED",
                slug: "switch-oled",
                description: "Портативная консоль с OLED экраном",
                price: 34990,
                oldPrice: 37990,
                stock: 25,
                isActive: true,
                categoryId: insertedCategories[5].id,
                brandId: insertedBrands[8].id,
                images: [
                    "https://best-magazin.com/image/cache/catalog/product/Igrovie-pristavki/portativnie/igrovaya-pristavka-nintendo-switch-oled-neon-cena-800x800.jpg",
                ],
                specifications: {
                    screen: '7" OLED',
                    storage: "64GB",
                    portability: "Yes",
                },
                rating: 4.7,
                reviewCount: 324,
            },
            {
                name: "Nintendo Switch Lite",
                slug: "switch-lite",
                description: "Компактная версия Switch",
                price: 21990,
                oldPrice: 24990,
                stock: 35,
                isActive: true,
                categoryId: insertedCategories[5].id,
                brandId: insertedBrands[8].id,
                images: [
                    "https://www.iport.ru/_next/image/?url=https%3A%2F%2Fcdn.iport.ru%2Fiblock%2Fa38%2Fa38c23f368e127a31fd2f820f9e8392a%2Fd9a169fc5ab719d6c275dfc937a48b84.jpg&w=1080&q=80",
                ],
                specifications: {
                    screen: '5.5"',
                    storage: "32GB",
                    portability: "Yes",
                },
                rating: 4.5,
                reviewCount: 213,
            },
            {
                name: "PlayStation VR2",
                slug: "ps-vr2",
                description: "Шлем виртуальной реальности для PS5",
                price: 59990,
                oldPrice: 64990,
                stock: 12,
                isActive: true,
                categoryId: insertedCategories[5].id,
                brandId: insertedBrands[2].id,
                images: [
                    "https://best-magazin.com/image/cache/catalog/product/Igrovie-pristavki/vr%20%20/shlem-virtualnoy-realnosti-sony-playstation-vr2-800x800.jpg",
                ],
                specifications: {
                    resolution: "4K HDR",
                    tracking: "Inside-out",
                    refreshRate: "120Hz",
                },
                rating: 4.6,
                reviewCount: 87,
            },
            {
                name: "Steam Deck 512GB",
                slug: "steam-deck-512",
                description: "Портативный ПК для игр",
                price: 64990,
                oldPrice: 69990,
                stock: 10,
                isActive: true,
                categoryId: insertedCategories[5].id,
                brandId: insertedBrands[5].id,
                images: [
                    "https://indexiq.ru/storage/photo/resized/xy_1200x1200/e/06gyk83a7sop0k5_7ad012e2.jpg.webp",
                ],
                specifications: {
                    screen: '7"',
                    storage: "512GB NVMe",
                    os: "SteamOS",
                },
                rating: 4.7,
                reviewCount: 156,
            },
            {
                name: "Steam Deck 256GB",
                slug: "steam-deck-256",
                description: "Портативный ПК для игр",
                price: 54990,
                oldPrice: 59990,
                stock: 15,
                isActive: true,
                categoryId: insertedCategories[5].id,
                brandId: insertedBrands[5].id,
                images: [
                    "https://oceania.istudio-msk.ru/upload/iblock/30f/5y3f8v9o1iic3azyofltxapuq9h3yoqd.webp",
                ],
                specifications: {
                    screen: '7"',
                    storage: "256GB NVMe",
                    os: "SteamOS",
                },
                rating: 4.7,
                reviewCount: 142,
            },
            {
                name: "Steam Deck 64GB",
                slug: "steam-deck-64",
                description: "Базовая версия Steam Deck",
                price: 44990,
                oldPrice: 49990,
                stock: 20,
                isActive: true,
                categoryId: insertedCategories[5].id,
                brandId: insertedBrands[5].id,
                images: [
                    "https://images.unsplash.com/photo-1621252179027-94459d63705b?w=500",
                ],
                specifications: {
                    screen: '7"',
                    storage: "64GB eMMC",
                    os: "SteamOS",
                },
                rating: 4.6,
                reviewCount: 178,
            },

            // УМНЫЕ ЧАСЫ (10 товаров)
            {
                name: "Apple Watch Series 9",
                slug: "apple-watch-series-9",
                description: "Современные умные часы с Always-On дисплеем",
                price: 44990,
                oldPrice: 49990,
                stock: 25,
                isActive: true,
                categoryId: insertedCategories[4].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://best-magazin.com/image/cache/catalog/product/Apple%20iWatch/Series%209/apple-watch-series-9-midnight-aluminium-case-45mm-with-midnight-sport-band-800x800.jpg",
                ],
                specifications: {
                    display: "45mm",
                    battery: "18 hours",
                    waterResistance: "50m",
                },
                rating: 4.8,
                reviewCount: 234,
            },
            {
                name: "Apple Watch Ultra 2",
                slug: "apple-watch-ultra-2",
                description: "Экстремальные часы для спорта и приключений",
                price: 89990,
                oldPrice: 94990,
                stock: 12,
                isActive: true,
                categoryId: insertedCategories[4].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://apple-rostov.com/image/cache/catalog/Apple-watch-ultra-2-2023/apple-watch-ultra-2-black-2024-49mm-titanium-case-remeshok-blue-trail-800x800-product_popup.jpg",
                ],
                specifications: {
                    display: "49mm",
                    battery: "36 hours",
                    waterResistance: "100m",
                },
                rating: 4.9,
                reviewCount: 127,
            },
            {
                name: "Samsung Galaxy Watch6",
                slug: "galaxy-watch6",
                description: "Флагманские часы для Android",
                price: 29990,
                oldPrice: 34990,
                stock: 30,
                isActive: true,
                categoryId: insertedCategories[4].id,
                brandId: insertedBrands[1].id,
                images: [
                    "https://hi-stores.ru/upload/iblock/8d3/evfu11dtl578wcb9dcr3qqowrpbq8mk2.jpg",
                ],
                specifications: {
                    display: "44mm",
                    battery: "40 hours",
                    waterResistance: "50m",
                },
                rating: 4.6,
                reviewCount: 178,
            },
            {
                name: "Samsung Galaxy Watch6 Classic",
                slug: "galaxy-watch6-classic",
                description: "Классические часы с вращающимся bezel",
                price: 39990,
                oldPrice: 44990,
                stock: 20,
                isActive: true,
                categoryId: insertedCategories[4].id,
                brandId: insertedBrands[1].id,
                images: [
                    "https://samsungstore-spb.ru/image/cache/catalog/watch-6-classic/samsung-galaxy-watch6-classic-1-800x800.jpeg",
                ],
                specifications: {
                    display: "47mm",
                    battery: "40 hours",
                    waterResistance: "50m",
                },
                rating: 4.7,
                reviewCount: 143,
            },
            {
                name: "Xiaomi Watch 2",
                slug: "xiaomi-watch-2",
                description: "Доступные умные часы с Wear OS",
                price: 16990,
                oldPrice: 19990,
                stock: 35,
                isActive: true,
                categoryId: insertedCategories[4].id,
                brandId: insertedBrands[3].id,
                images: [
                    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYxf4z9StS_HYGh2-ov_syP6wqwvESg1W4Uw&s",
                ],
                specifications: {
                    display: "46mm",
                    battery: "48 hours",
                    waterResistance: "50m",
                },
                rating: 4.4,
                reviewCount: 156,
            },
            {
                name: "Garmin Fenix 7",
                slug: "garmin-fenix-7",
                description: "Спортивные часы для профессионалов",
                price: 64990,
                oldPrice: 69990,
                stock: 10,
                isActive: true,
                categoryId: insertedCategories[4].id,
                brandId: insertedBrands[2].id,
                images: [
                    "https://magazin-sportlife.ru/uploads/images/2023/04/2f0e79279c23986e7cfe713871b46a35-md.jpg",
                ],
                specifications: {
                    display: "47mm",
                    battery: "18 days",
                    waterResistance: "100m",
                },
                rating: 4.8,
                reviewCount: 92,
            },
            {
                name: "Apple Watch SE 2",
                slug: "apple-watch-se-2",
                description: "Доступные Apple Watch",
                price: 29990,
                oldPrice: 32990,
                stock: 40,
                isActive: true,
                categoryId: insertedCategories[4].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://apple-rostov.com/image/cache/catalog/Apple-watch-SE-2-2022/apple-watch-se-2-2022-44-mm-silver-800x800-product_popup.jpg",
                ],
                specifications: {
                    display: "44mm",
                    battery: "18 hours",
                    waterResistance: "50m",
                },
                rating: 4.6,
                reviewCount: 267,
            },
            {
                name: "Huawei Watch GT 4",
                slug: "huawei-watch-gt-4",
                description: "Стильные часы с долгой работой",
                price: 24990,
                oldPrice: 27990,
                stock: 25,
                isActive: true,
                categoryId: insertedCategories[4].id,
                brandId: insertedBrands[3].id,
                images: [
                    "https://www.cifrus.ru/photos/big/huawei/huawei-watch-gt-4-46mm-serebryaniy-55020bmt-1.jpg",
                ],
                specifications: {
                    display: "46mm",
                    battery: "14 days",
                    waterResistance: "50m",
                },
                rating: 4.5,
                reviewCount: 134,
            },
            {
                name: "Amazfit GTR 4",
                slug: "amazfit-gtr-4",
                description: "Бюджетные часы с отличным функционалом",
                price: 14990,
                oldPrice: 16990,
                stock: 40,
                isActive: true,
                categoryId: insertedCategories[4].id,
                brandId: insertedBrands[3].id,
                images: [
                    "https://static.ru-mi.com/upload/resize_cache/iblock/f24/440_440_1/3u32uggvvnj6wafnbut507hwc6flc082.jpeg",
                ],
                specifications: {
                    display: "46mm",
                    battery: "14 days",
                    waterResistance: "50m",
                },
                rating: 4.4,
                reviewCount: 189,
            },
            {
                name: "Polar Vantage V3",
                slug: "polar-vantage-v3",
                description: "Часы для серьёзных тренировок",
                price: 54990,
                oldPrice: 59990,
                stock: 8,
                isActive: true,
                categoryId: insertedCategories[4].id,
                brandId: insertedBrands[2].id,
                images: [
                    "https://magazin-sportlife.ru/uploads/images/2024/02/fa9b6a022dcecb78c12d86ee7af714e9-md.jpg",
                ],
                specifications: {
                    display: "47mm",
                    battery: "8 days",
                    waterResistance: "100m",
                },
                rating: 4.7,
                reviewCount: 67,
            },

            // МОНИТОРЫ (10 товаров)
            {
                name: "LG UltraGear 27GR95U",
                slug: "lg-ultragear-27gr95u",
                description: "4K игровой монитор 144Hz",
                price: 89990,
                oldPrice: 99990,
                stock: 12,
                isActive: true,
                categoryId: insertedCategories[7].id,
                brandId: insertedBrands[4].id,
                images: [
                    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSl44Pmm5kazFO2wgudzAbESyw716D4PNKY8A&s",
                ],
                specifications: {
                    size: '27"',
                    resolution: "4K",
                    refreshRate: "144Hz",
                    panel: "IPS",
                },
                rating: 4.8,
                reviewCount: 94,
            },
            {
                name: "Samsung Odyssey G9",
                slug: "odyssey-g9",
                description: "Изогнутый ультраширокий монитор",
                price: 129990,
                oldPrice: 149990,
                stock: 8,
                isActive: true,
                categoryId: insertedCategories[7].id,
                brandId: insertedBrands[1].id,
                images: [
                    "https://hardprice.ru/images/g/product/3249/monitor-samsung-49-odyssey-g9-c49g95tssi-1.jpg",
                ],
                specifications: {
                    size: '49"',
                    resolution: "5120x1440",
                    refreshRate: "240Hz",
                    panel: "VA",
                },
                rating: 4.9,
                reviewCount: 76,
            },
            {
                name: "ASUS ROG Swift PG27AQDM",
                slug: "rog-swift-pg27aqdm",
                description: "OLED монитор для геймеров",
                price: 109990,
                oldPrice: 119990,
                stock: 10,
                isActive: true,
                categoryId: insertedCategories[7].id,
                brandId: insertedBrands[5].id,
                images: [
                    "https://microless.com/cdn/products/f25a7a2460014dccdad545f5ccefa534-hi.jpg",
                ],
                specifications: {
                    size: '27"',
                    resolution: "1440p",
                    refreshRate: "240Hz",
                    panel: "OLED",
                },
                rating: 4.9,
                reviewCount: 62,
            },
            {
                name: "Dell UltraSharp U2723QE",
                slug: "ultrasharp-u2723qe",
                description: "Профессиональный 4K монитор",
                price: 79990,
                oldPrice: 89990,
                stock: 15,
                isActive: true,
                categoryId: insertedCategories[7].id,
                brandId: insertedBrands[6].id,
                images: [
                    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUP84rKqYEQgacVVpSh88aOgzgKtWglzM2NA&s",
                ],
                specifications: {
                    size: '27"',
                    resolution: "4K",
                    refreshRate: "60Hz",
                    panel: "IPS",
                },
                rating: 4.7,
                reviewCount: 87,
            },
            {
                name: "LG 27UP850",
                slug: "lg-27up850",
                description: "Универсальный 4K монитор",
                price: 44990,
                oldPrice: 49990,
                stock: 20,
                isActive: true,
                categoryId: insertedCategories[7].id,
                brandId: insertedBrands[4].id,
                images: [
                    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNSsJXc_Du9aSJ6nyNtHBOe-VJyIHmvU5WWw&s",
                ],
                specifications: {
                    size: '27"',
                    resolution: "4K",
                    refreshRate: "60Hz",
                    panel: "IPS",
                },
                rating: 4.6,
                reviewCount: 134,
            },
            {
                name: "Samsung ViewFinity S8",
                slug: "viewfinity-s8",
                description: "5K монитор для творчества",
                price: 149990,
                oldPrice: 169990,
                stock: 6,
                isActive: true,
                categoryId: insertedCategories[7].id,
                brandId: insertedBrands[1].id,
                images: [
                    "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500",
                ],
                specifications: {
                    size: '32"',
                    resolution: "5K",
                    refreshRate: "60Hz",
                    panel: "IPS",
                },
                rating: 4.7,
                reviewCount: 43,
            },
            {
                name: "ASUS TUF Gaming VG27AQ",
                slug: "tuf-gaming-vg27aq",
                description: "Популярный игровой монитор",
                price: 34990,
                oldPrice: 39990,
                stock: 25,
                isActive: true,
                categoryId: insertedCategories[7].id,
                brandId: insertedBrands[5].id,
                images: [
                    "https://main-cdn.sbermegamarket.ru/big1/hlr-system/-3/47/52/56/86/48/100026257184b0.jpg",
                ],
                specifications: {
                    size: '27"',
                    resolution: "1440p",
                    refreshRate: "165Hz",
                    panel: "IPS",
                },
                rating: 4.6,
                reviewCount: 267,
            },
            {
                name: "AOC 24G2SP",
                slug: "aoc-24g2sp",
                description: "Бюджетный игровой монитор",
                price: 19990,
                oldPrice: 22990,
                stock: 30,
                isActive: true,
                categoryId: insertedCategories[7].id,
                brandId: insertedBrands[5].id,
                images: [
                    "https://cdn.citilink.ru/LBKUjjiDURazb0sQJ_DkOvjC30llxmKM4OAwckjGuV0/resizing_type:fit/gravity:sm/width:1200/height:750/plain/product-images/1adcd900-a003-4038-abfa-1233e8193f56.jpg",
                ],
                specifications: {
                    size: '24"',
                    resolution: "1080p",
                    refreshRate: "165Hz",
                    panel: "IPS",
                },
                rating: 4.5,
                reviewCount: 312,
            },
            {
                name: "Dell Alienware AW3423DWF",
                slug: "alienware-aw3423dwf",
                description: "QD-OLED изогнутый монитор",
                price: 119990,
                oldPrice: 129990,
                stock: 7,
                isActive: true,
                categoryId: insertedCategories[7].id,
                brandId: insertedBrands[6].id,
                images: [
                    "https://static.apltech.ru/uploads/products/12/464704/359bdf84bb4146578ccd49474de86e06@1000.jpg",
                ],
                specifications: {
                    size: '34"',
                    resolution: "1440p",
                    refreshRate: "165Hz",
                    panel: "QD-OLED",
                },
                rating: 4.9,
                reviewCount: 58,
            },
            {
                name: "LG 24MP400",
                slug: "lg-24mp400",
                description: "Простой офисный монитор",
                price: 14990,
                oldPrice: 16990,
                stock: 40,
                isActive: true,
                categoryId: insertedCategories[7].id,
                brandId: insertedBrands[4].id,
                images: [
                    "https://media.us.lg.com/transform/ecomm-PDPGallery-1100x730/96b7c20d-c815-4ac7-990c-b2aff4d1b4b5/md08000731-Z2-jpg?io=transform:fill,width:1536",
                ],
                specifications: {
                    size: '24"',
                    resolution: "1080p",
                    refreshRate: "75Hz",
                    panel: "IPS",
                },
                rating: 4.3,
                reviewCount: 189,
            },

            // ПЛАНШЕТЫ (10 товаров)
            {
                name: "Apple iPad Pro 12.9 M2",
                slug: "ipad-pro-12-9-m2",
                description: "Мощнейший планшет с Liquid Retina XDR",
                price: 129990,
                oldPrice: 139990,
                stock: 15,
                isActive: true,
                categoryId: insertedCategories[2].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://myapple61.ru/image/cache/catalog/ipad/ipad-pro-12-9-m2-2022/ipad-pro-12-9-m2-2022-wifi-256-space-gray-800x800-product_thumb.jpg",
                ],
                specifications: {
                    screen: '12.9"',
                    storage: "128GB",
                    processor: "M2",
                },
                rating: 4.9,
                reviewCount: 167,
            },
            {
                name: "Apple iPad Pro 11 M2",
                slug: "ipad-pro-11-m2",
                description: "Компактный профессиональный планшет",
                price: 99990,
                oldPrice: 109990,
                stock: 20,
                isActive: true,
                categoryId: insertedCategories[2].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://apple-rostov.com/image/cache/catalog/Apple-iPad-Pro-11-M2-2022/apple-ipad-pro-11-m2-wi%E2%80%91fi-512-gb-silver-2022-3-800x800-product_popup.jpg",
                ],
                specifications: {
                    screen: '11"',
                    storage: "128GB",
                    processor: "M2",
                },
                rating: 4.8,
                reviewCount: 143,
            },
            {
                name: "Apple iPad Air 5",
                slug: "ipad-air-5",
                description: "Универсальный планшет с M1",
                price: 69990,
                oldPrice: 74990,
                stock: 25,
                isActive: true,
                categoryId: insertedCategories[2].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://apple-rostov.com/image/cache/catalog/apple-ipad-air-5/apple-ipad-air-5-2022-wi-fi-cellular-64-gb-blue-800x800-product_popup.jpg",
                ],
                specifications: {
                    screen: '10.9"',
                    storage: "64GB",
                    processor: "M1",
                },
                rating: 4.7,
                reviewCount: 234,
            },
            {
                name: "Samsung Galaxy Tab S9 Ultra",
                slug: "galaxy-tab-s9-ultra",
                description: "Флагманский Android планшет",
                price: 119990,
                oldPrice: 129990,
                stock: 12,
                isActive: true,
                categoryId: insertedCategories[2].id,
                brandId: insertedBrands[1].id,
                images: [
                    "https://allohastore.ru/image/cache/catalog/samsung/tab%20s9%20ultra/020-galaxy-tabs9ultra-beige-combo-800x800.jpg",
                ],
                specifications: {
                    screen: '14.6"',
                    storage: "256GB",
                    processor: "Snapdragon 8 Gen 2",
                },
                rating: 4.8,
                reviewCount: 98,
            },
            {
                name: "Samsung Galaxy Tab S9",
                slug: "galaxy-tab-s9",
                description: "Премиальный планшет с S Pen",
                price: 89990,
                oldPrice: 94990,
                stock: 18,
                isActive: true,
                categoryId: insertedCategories[2].id,
                brandId: insertedBrands[1].id,
                images: [
                    "https://best-magazin.com/image/cache/catalog/product/Planshety/Samsung/tab-s9/planshet-samsung-galaxy-tab-s9-gray-sm-x716b-foto-800x800.jpg",
                ],
                specifications: {
                    screen: '11"',
                    storage: "128GB",
                    processor: "Snapdragon 8 Gen 2",
                },
                rating: 4.7,
                reviewCount: 112,
            },
            {
                name: "Apple iPad 10",
                slug: "ipad-10",
                description: "Базовый iPad с современным дизайном",
                price: 44990,
                oldPrice: 49990,
                stock: 30,
                isActive: true,
                categoryId: insertedCategories[2].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://apple-rostov.com/image/cache/catalog/Apple-iPad-10-2022/apple-ipad-10-wi%E2%80%91fi-256-gb-blue-2-800x800-product_popup.jpg",
                ],
                specifications: {
                    screen: '10.9"',
                    storage: "64GB",
                    processor: "A14",
                },
                rating: 4.6,
                reviewCount: 289,
            },
            {
                name: "Xiaomi Pad 6",
                slug: "xiaomi-pad-6",
                description: "Отличный планшет за свои деньги",
                price: 34990,
                oldPrice: 39990,
                stock: 25,
                isActive: true,
                categoryId: insertedCategories[2].id,
                brandId: insertedBrands[3].id,
                images: [
                    "https://hi-stores.ru/upload/iblock/076/qsrchvkg3vsnke076ed7g5l0ysrseg2h.jpg",
                ],
                specifications: {
                    screen: '11"',
                    storage: "128GB",
                    processor: "Snapdragon 870",
                },
                rating: 4.5,
                reviewCount: 156,
            },
            {
                name: "Samsung Galaxy Tab A9+",
                slug: "galaxy-tab-a9-plus",
                description: "Доступный планшет Samsung",
                price: 24990,
                oldPrice: 27990,
                stock: 35,
                isActive: true,
                categoryId: insertedCategories[2].id,
                brandId: insertedBrands[1].id,
                images: [
                    "https://vladimir.ibrat.ru/upload/cssinliner_webp/iblock/114/rwirznrnkneb0svv5zhqguv1cmu99sof.webp",
                ],
                specifications: {
                    screen: '11"',
                    storage: "64GB",
                    processor: "Snapdragon 695",
                },
                rating: 4.3,
                reviewCount: 134,
            },
            {
                name: "Apple iPad mini 6",
                slug: "ipad-mini-6",
                description: "Компактный iPad",
                price: 54990,
                oldPrice: 59990,
                stock: 20,
                isActive: true,
                categoryId: insertedCategories[2].id,
                brandId: insertedBrands[0].id,
                images: [
                    "https://mobilo4ka.ru/image/cache/2ecd770821f56974a2ddae8fbb9149e1.jpg",
                ],
                specifications: {
                    screen: '8.3"',
                    storage: "64GB",
                    processor: "A15",
                },
                rating: 4.7,
                reviewCount: 178,
            },
            {
                name: "Lenovo Tab P12",
                slug: "lenovo-tab-p12",
                description: "Большой планшет для работы",
                price: 44990,
                oldPrice: 49990,
                stock: 15,
                isActive: true,
                categoryId: insertedCategories[2].id,
                brandId: insertedBrands[6].id,
                images: [
                    "https://mobile-review.com/all/wp-content/uploads/2021/09/lenovo-tab-p12-pro_front_back_art_markup-800x450.jpg",
                ],
                specifications: {
                    screen: '12.7"',
                    storage: "128GB",
                    processor: "Dimensity 7050",
                },
                rating: 4.4,
                reviewCount: 87,
            },
            // CANON
            // {
            //     name: "Canon EOS R5",
            //     slug: "canon-eos-r5",
            //     description:
            //         "Профессиональная беззеркальная камера 45 МП с 8K видео",
            //     price: 349990,
            //     oldPrice: 379990,
            //     stock: 8,
            //     isActive: true,
            //     categoryId: 28, // Фотоаппараты
            //     brandId: 8, // Canon
            //     images: [
            //         "https://magprofoto.ru/21365-thickbox_default/fotoapparat-canon-eos-r5-s-obektivom-rf-24-70-mm-f28-l-is-usm.jpg",
            //     ],
            //     specifications: {
            //         sensor: "45MP Full-Frame",
            //         video: "8K 30fps",
            //         iso: "100-51200",
            //     },
            //     rating: 4.9,
            //     reviewCount: 67,
            // },
            // {
            //     name: "Canon EOS R6 Mark II",
            //     slug: "canon-eos-r6-mark-ii",
            //     description: "Универсальная камера для фото и видео 24.2 МП",
            //     price: 249990,
            //     oldPrice: 269990,
            //     stock: 12,
            //     isActive: true,
            //     categoryId: 28,
            //     brandId: 8,
            //     images: [
            //         "https://www.yarkiy.ru/system/uploads/preview/photo_storage/232306/EOS-R6-Mark-II-FRT.jpg",
            //     ],
            //     specifications: {
            //         sensor: "24.2MP Full-Frame",
            //         video: "4K 60fps",
            //         iso: "100-102400",
            //     },
            //     rating: 4.8,
            //     reviewCount: 54,
            // },

            // // SONY
            // {
            //     name: "Sony Alpha A7 IV",
            //     slug: "sony-alpha-a7-iv",
            //     description:
            //         "Гибридная камера 33 МП с отличной автофокусировкой",
            //     price: 279990,
            //     oldPrice: 299990,
            //     stock: 10,
            //     isActive: true,
            //     categoryId: 28,
            //     brandId: 2, // Sony
            //     images: [
            //         "https://www.yarkiy.ru/system/uploads/preview/photo_storage/227831/Sony-a7-iv-11.jpg",
            //     ],
            //     specifications: {
            //         sensor: "33MP Full-Frame",
            //         video: "4K 60fps",
            //         iso: "100-51200",
            //     },
            //     rating: 4.9,
            //     reviewCount: 89,
            // }, // ЗАРЯДКИ И КАБЕЛИ
            // {
            //     name: "Apple MagSafe Charger",
            //     slug: "apple-magsafe-charger",
            //     description: "Беспроводная зарядка для iPhone до 15W",
            //     price: 5990,
            //     oldPrice: 6990,
            //     stock: 50,
            //     isActive: true,
            //     categoryId: 30, // Аксессуары
            //     brandId: 0, // Apple
            //     images: [
            //         "https://apple-nova.ru/files/thumb/item/MHXH3_1.jpg?s=800,800,800,800",
            //     ],
            //     specifications: {
            //         power: "15W",
            //         type: "Wireless",
            //         compatibility: "iPhone 12+",
            //     },
            //     rating: 4.6,
            //     reviewCount: 234,
            // },
            // {
            //     name: "Anker PowerCore 20000mAh",
            //     slug: "anker-powercore-20000",
            //     description: "Мощный пауэрбанк с быстрой зарядкой",
            //     price: 4990,
            //     oldPrice: 5990,
            //     stock: 40,
            //     isActive: true,
            //     categoryId: 30,
            //     brandId: 6, // Anker (можно заменить на существующий бренд)
            //     images: [
            //         "https://i0.wp.com/beirutco.com.lb/wp-content/uploads/2021/11/Anker-PowerCore-select-20000-888.jpg?fit=800%2C800&ssl=1",
            //     ],
            //     specifications: {
            //         capacity: "20000mAh",
            //         ports: "2x USB-A",
            //         fastCharging: "Yes",
            //     },
            //     rating: 4.7,
            //     reviewCount: 312,
            // },

            // // ЧЕХЛЫ И ЗАЩИТА
            // {
            //     name: "Spigen iPhone 15 Pro Case",
            //     slug: "spigen-iphone-15-pro-case",
            //     description: "Защитный чехол с усиленными углами",
            //     price: 1990,
            //     oldPrice: 2490,
            //     stock: 100,
            //     isActive: true,
            //     categoryId: 30,
            //     brandId: 0, // Apple (или создай бренд Spigen)
            //     images: [
            //         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTADDrOMMNwb45DdUSljjxHWL3IbtPe4zh2WQ&shttps://images.unsplash.com/photo-1603313011101-320f26a4f6f6?w=500",
            //     ],
            //     specifications: {
            //         material: "TPU",
            //         color: "Black",
            //         protection: "Military Grade",
            //     },
            //     rating: 4.5,
            //     reviewCount: 178,
            // },
        ];

        console.log("📦 Добавляем продукты...");
        const insertedProducts = await db
            .insert(products)
            .values(productsData)
            .returning();
        console.log(`✅ Добавлено ${insertedProducts.length} продуктов`);

        // 4. Отзывы (50 отзывов)
        const reviewsData = [
            {
                userId: 1,
                productId: insertedProducts[0].id,
                rating: 5,
                comment: "Отличный телефон! Камера просто супер!",
            },
            {
                userId: 2,
                productId: insertedProducts[0].id,
                rating: 5,
                comment: "Лучший iPhone который у меня был",
            },
            {
                userId: 3,
                productId: insertedProducts[0].id,
                rating: 4,
                comment: "Дорого, но качество на высоте",
            },
            {
                userId: 1,
                productId: insertedProducts[15].id,
                rating: 5,
                comment: "MacBook просто летает! M3 чип мощный",
            },
            {
                userId: 4,
                productId: insertedProducts[15].id,
                rating: 5,
                comment: "Идеален для работы с видео",
            },
            {
                userId: 2,
                productId: insertedProducts[30].id,
                rating: 5,
                comment: "AirPods Pro 2 - лучшие наушники",
            },
            {
                userId: 5,
                productId: insertedProducts[30].id,
                rating: 4,
                comment: "Шумоподавление отличное, но цена кусается",
            },
            {
                userId: 3,
                productId: insertedProducts[45].id,
                rating: 5,
                comment: "PS5 - это что-то! Графика нереальная",
            },
            {
                userId: 1,
                productId: insertedProducts[45].id,
                rating: 5,
                comment: "Наконец-то купил, очень доволен!",
            },
            {
                userId: 6,
                productId: insertedProducts[55].id,
                rating: 5,
                comment: "Apple Watch лучшие умные часы",
            },
            {
                userId: 2,
                productId: insertedProducts[55].id,
                rating: 4,
                comment: "Батарея могла бы быть получше",
            },
            {
                userId: 7,
                productId: insertedProducts[65].id,
                rating: 5,
                comment: "Монитор просто огонь! 4K 144Hz",
            },
            {
                userId: 4,
                productId: insertedProducts[65].id,
                rating: 5,
                comment: "Для игр и работы идеально",
            },
            {
                userId: 5,
                productId: insertedProducts[75].id,
                rating: 5,
                comment: "iPad Pro заменяет мне ноутбук",
            },
            {
                userId: 8,
                productId: insertedProducts[75].id,
                rating: 4,
                comment: "Мощный, но iPadOS ограничивает",
            },
            {
                userId: 1,
                productId: insertedProducts[3].id,
                rating: 5,
                comment: "Samsung S24 Ultra - топ!",
            },
            {
                userId: 9,
                productId: insertedProducts[3].id,
                rating: 5,
                comment: "S Pen очень удобен",
            },
            {
                userId: 10,
                productId: insertedProducts[18].id,
                rating: 5,
                comment: "ASUS ROG - лучший игровой ноут",
            },
            {
                userId: 2,
                productId: insertedProducts[18].id,
                rating: 4,
                comment: "Греется под нагрузкой, но тянет всё",
            },
            {
                userId: 3,
                productId: insertedProducts[32].id,
                rating: 5,
                comment: "Sony WH-1000XM5 - лучшие для путешествий",
            },
            {
                userId: 11,
                productId: insertedProducts[32].id,
                rating: 5,
                comment: "Шумодав просто космос",
            },
            {
                userId: 4,
                productId: insertedProducts[47].id,
                rating: 5,
                comment: "Xbox Series X мощный и тихий",
            },
            {
                userId: 12,
                productId: insertedProducts[47].id,
                rating: 4,
                comment: "Game Pass отличная подписка",
            },
            {
                userId: 5,
                productId: insertedProducts[57].id,
                rating: 5,
                comment: "Galaxy Watch6 удобные и красивые",
            },
            {
                userId: 13,
                productId: insertedProducts[57].id,
                rating: 4,
                comment: "С Android работают отлично",
            },
            {
                userId: 6,
                productId: insertedProducts[67].id,
                rating: 5,
                comment: "Samsung Odyssey G9 - это космос!",
            },
            {
                userId: 14,
                productId: insertedProducts[67].id,
                rating: 5,
                comment: "Изогнутый экран меняет всё",
            },
            {
                userId: 7,
                productId: insertedProducts[77].id,
                rating: 5,
                comment: "iPad Air - золотая середина",
            },
            {
                userId: 15,
                productId: insertedProducts[77].id,
                rating: 4,
                comment: "Отличный планшет за свои деньги",
            },
            {
                userId: 8,
                productId: insertedProducts[5].id,
                rating: 5,
                comment: "Xiaomi 14 Ultra камера топ!",
            },
            {
                userId: 16,
                productId: insertedProducts[5].id,
                rating: 4,
                comment: "Leica оптика радует",
            },
            {
                userId: 9,
                productId: insertedProducts[20].id,
                rating: 5,
                comment: "MacBook Pro 16 - монстр!",
            },
            {
                userId: 17,
                productId: insertedProducts[20].id,
                rating: 5,
                comment: "Для работы с 3D идеально",
            },
            {
                userId: 10,
                productId: insertedProducts[35].id,
                rating: 5,
                comment: "AirPods Max - премиум звук",
            },
            {
                userId: 18,
                productId: insertedProducts[35].id,
                rating: 3,
                comment: "Тяжёлые, но звук отличный",
            },
            {
                userId: 1,
                productId: insertedProducts[48].id,
                rating: 5,
                comment: "Switch OLED лучший для поездок",
            },
            {
                userId: 19,
                productId: insertedProducts[48].id,
                rating: 5,
                comment: "Zelda на OLED это что-то!",
            },
            {
                userId: 2,
                productId: insertedProducts[58].id,
                rating: 5,
                comment: "Apple Watch Ultra 2 - для экстремалов",
            },
            {
                userId: 20,
                productId: insertedProducts[58].id,
                rating: 5,
                comment: "Батарея держит долго",
            },
            {
                userId: 3,
                productId: insertedProducts[68].id,
                rating: 5,
                comment: "ASUS OLED монитор - картинка идеальна",
            },
            {
                userId: 21,
                productId: insertedProducts[68].id,
                rating: 5,
                comment: "240Hz OLED - это будущее",
            },
            {
                userId: 4,
                productId: insertedProducts[78].id,
                rating: 5,
                comment: "Galaxy Tab S9 Ultra - огромный!",
            },
            {
                userId: 22,
                productId: insertedProducts[78].id,
                rating: 4,
                comment: "Для рисования супер",
            },
            {
                userId: 5,
                productId: insertedProducts[8].id,
                rating: 5,
                comment: "Z Fold 5 - будущее смартфонов",
            },
            {
                userId: 23,
                productId: insertedProducts[8].id,
                rating: 4,
                comment: "Дорогой, но инновационный",
            },
            {
                userId: 6,
                productId: insertedProducts[23].id,
                rating: 5,
                comment: "ThinkPad - надёжность",
            },
            {
                userId: 24,
                productId: insertedProducts[23].id,
                rating: 5,
                comment: "Клавиатура лучшая",
            },
            {
                userId: 7,
                productId: insertedProducts[38].id,
                rating: 5,
                comment: "Sony WF-1000XM5 компактные и мощные",
            },
            {
                userId: 25,
                productId: insertedProducts[38].id,
                rating: 4,
                comment: "Звук отличный, цена высокая",
            },
            {
                userId: 8,
                productId: insertedProducts[50].id,
                rating: 5,
                comment: "Steam Deck - ПК в кармане",
            },
            {
                userId: 26,
                productId: insertedProducts[50].id,
                rating: 4,
                comment: "Батарея слабовата, но играется",
            },
        ];

        console.log("💬 Добавляем отзывы...");
        await db.insert(reviews).values(reviewsData);
        console.log(`✅ Добавлено ${reviewsData.length} отзывов`);

        console.log("\n✅ ✅ ✅ Seed завершен успешно! ✅ ✅ ✅");
        console.log(
            `📊 Итого: ${insertedCategories.length} категорий, ${insertedBrands.length} брендов, ${insertedProducts.length} товаров, ${reviewsData.length} отзывов`,
        );
    } catch (error) {
        console.error("❌ Ошибка при seed:", error);
    } finally {
        await client.end();
    }
};

seedDatabase();
